INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_1", "url": "http://spoofhost:7890/dir1/dir2/1"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_2", "url": "http://spoofhost:7890/dir1/dir2/2"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_3", "url": "http://spoofhost:7890/dir1/dir2/3"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_4", "url": "http://spoofhost:7890/dir1/dir2/4"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_5", "url": "http://spoofhost:7890/dir1/dir2/5"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_6", "url": "http://spoofhost:7890/dir1/dir2/6"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_7", "url": "http://spoofhost:7890/dir1/dir2/7"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_8", "url": "http://spoofhost:7890/dir1/dir2/8"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_9", "url": "http://spoofhost:7890/dir1/dir2/9"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_125641", "destination_id": "test_destination_5", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_165142", "destination_id": "test_destination_7", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_102283", "destination_id": "test_destination_8", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_135194", "destination_id": "test_destination_6", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_179835", "destination_id": "test_destination_9", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_177466", "destination_id": "test_destination_6", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_129867", "destination_id": "test_destination_9", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_138098", "destination_id": "test_destination_1", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_178279", "destination_id": "test_destination_6", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_1772510", "destination_id": "test_destination_7", "sensor_type": "test"}');
