INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_1", "url": "http://spoofhost:7890/dir1/dir2/1"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_2", "url": "http://spoofhost:7890/dir1/dir2/2"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_3", "url": "http://spoofhost:7890/dir1/dir2/3"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_4", "url": "http://spoofhost:7890/dir1/dir2/4"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_5", "url": "http://spoofhost:7890/dir1/dir2/5"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_6", "url": "http://spoofhost:7890/dir1/dir2/6"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_7", "url": "http://spoofhost:7890/dir1/dir2/7"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_8", "url": "http://spoofhost:7890/dir1/dir2/8"}');
INSERT INTO csn_destination (info) VALUES ('{ "destination_id": "test_destination_9", "url": "http://spoofhost:7890/dir1/dir2/9"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_109361", "destination_id": "7", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_102542", "destination_id": "2", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_146033", "destination_id": "3", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_144814", "destination_id": "7", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_124075", "destination_id": "9", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_177466", "destination_id": "5", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_111577", "destination_id": "7", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_124258", "destination_id": "1", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_104919", "destination_id": "4", "sensor_type": "test"}');
INSERT INTO csn_sensor (info) VALUES ('{ "sensor_id": "test_sensor_1464310", "destination_id": "8", "sensor_type": "test"}');
